[versions]
kotlin = "2.2.21"
dokka = "2.1.0"
maven-publish-plugin = "0.35.0"
sonarqube = "7.2.2.6593"
kraftsql-core = "0.0.9-SNAPSHOT"
google-cloud-libraries = "26.72.0"
jsonpath = "2.10.0"
apache-commons-csv = "1.14.1"
slf4j = "2.0.17"
junit = "6.0.1"
kotest = "6.0.7"
mockito = "6.1.0"
kover = "0.9.3"

[libraries]
maven-publish-plugin = { group = "com.vanniktech.maven.publish", name = "com.vanniktech.maven.publish.gradle.plugin", version.ref = "maven-publish-plugin" }
kraftsql-core = { group = "rocks.frieler.kraftsql", name = "kraftsql", version.ref = "kraftsql-core" }
google-cloud-libraries-bom = { group = "com.google.cloud", name = "libraries-bom", version.ref = "google-cloud-libraries" }
bigquery-client = { group = "com.google.cloud", name = "google-cloud-bigquery" }
jsonpath = { group = "com.jayway.jsonpath", name = "json-path", version.ref = "jsonpath" }
apache-commons-csv = { group = "org.apache.commons", name = "commons-csv", version.ref = "apache-commons-csv" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
junit5-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
kraftsql-core-testing = { group = "rocks.frieler.kraftsql", name = "kraftsql-testing", version.ref = "kraftsql-core" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
